# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_taller',
                'doc_host': 'https://CristopherFoster.github.io',
                'git_url': 'https://github.com/CristopherFoster/nbdev_taller',
                'lib_path': 'nbdev_taller'},
  'syms': {'nbdev_taller.core': {'nbdev_taller.core.foo': ('core.html#foo', 'nbdev_taller/core.py')}}}
